export AWS_ACCESS_KEY_ID="YOUR AWK KEY"
export AWS_SECRET_ACCESS_KEY="YOUR AWS SECRET KEY"

export RDS_PORT="YOUR DB PORT"
export RDS_PASSWORD="YOUR DB PASSWORD"
export RDS_USERNAME="YOUR USER NAME"
export RDS_DB_NAME="YOUR DB NAME"
export RDS_HOSTNAME="YOUR DB HOSTNAME"
